---
name: Set up github action
description: Get the token for the github action and set git parameters so these credentials can be used on the repository
inputs:
  APP_ID:
    description: Github app ID
    required: true
  APP_PRIVATE_KEY:
    description: Private key for the github app
    required: true
runs:
  using: composite
  steps:
    - name: get app token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        # required
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.APP_PRIVATE_KEY }}
    - name: check out the repo using the token
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    - name: Get GitHub App User ID
      id: get-user-id
      shell: bash
      run: |
        USER_ID="$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)"
        echo user-id="$USER_ID" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Set git config for bot user
      run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
